Proj4Me.Web/Controllers/ColaboradorController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Proj4Me.Application.Interfaces;
using Proj4Me.Application.ViewModels;
using Proj4Me.Domain.Core.Notification;
using Proj4Me.Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Proj4Me.Web.Controllers
{
  
  public class ColaboradorController : BaseController
  {
    private readonly IColaboradorAppService _colaboradorAppService;

    public ColaboradorController(IColaboradorAppService colaboradorAppService,
                                 IDomainNotificationHandler<DomainNotification> notifications,
                                 IUser user) : base(notifications, user)
    {
      _colaboradorAppService = colaboradorAppService;
    }


    [Route("Listar-Colaboradores")]
    public IActionResult Index()
    {
      return View(_colaboradorAppService.GetAll());
    }

    [Route("dados-do-colaborador/{id:guid}")]
    public IActionResult Details(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var colaboradorViewModel = _colaboradorAppService.GetColaboradorById(id.Value);
      if (colaboradorViewModel == null)
      {
        return NotFound();
      }

      return View(colaboradorViewModel);
    }

    [Route("novo-colaborador")]
    public IActionResult Create()
    {
      return View();
    }

     [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("novo-colaborador")]
    public IActionResult Create(ColaboradorViewModel colaboradorViewModel)
    {
      if (!ModelState.IsValid) return View(colaboradorViewModel);

      _colaboradorAppService.Register(colaboradorViewModel);

      return View(colaboradorViewModel);
    }
   
    [Route("editar-colaborador/{id:guid}")]
    public IActionResult Edit(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var colaboradorViewModel = _colaboradorAppService.GetColaboradorById(id.Value);

      if (colaboradorViewModel == null)
      {
        return NotFound();
      }

      return View(colaboradorViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("editar-colaborador/{id:guid}")]
    public IActionResult Edit(ColaboradorViewModel colaboradorViewModel)
    {
      if (!ModelState.IsValid) return View(colaboradorViewModel);

      _colaboradorAppService.Update(colaboradorViewModel);

      // validar se a operacao ocorreu com sucesso

      return View(colaboradorViewModel);
    }

    [Route("editar-colaborador/{id:guid}")]
    public IActionResult Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var colaboradorViewModel = _colaboradorAppService.GetColaboradorById(id.Value);

      if (colaboradorViewModel == null)
      {
        return NotFound();
      }

      return View(colaboradorViewModel);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Route("editar-colaborador/{id:guid}")]
    public IActionResult DeleteConfirmed(Guid id)
    {
      _colaboradorAppService.Remove(id);

      //return RedirectToAction("Index");
      return RedirectToAction(nameof(Index));
    }
  }
}

Proj4Me.Web/Controllers/PerfilController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proj4Me.Application.Interfaces;
using Proj4Me.Application.ViewModels;

namespace Proj4Me.Web.Controllers
{
  public class PerfilController : Controller
  {
    private readonly IPerfilAppService _perfilAppService;

    public PerfilController(IPerfilAppService perfilAppService)
    {
      _perfilAppService = perfilAppService;
    }

    // GET: Perfil
    //[Route("")]
    [Route("listar-perfis")]
    public IActionResult Index()
    {
      return View(_perfilAppService.GetAll());
    }

    // GET: Perfil/Details/5
    [Route("dados-do-perfil/{id:guid}")]
    public IActionResult Details(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var perfilViewModel = _perfilAppService.GetPerfilById(id.Value);
      if (perfilViewModel == null)
      {
        return NotFound();
      }

      return View(perfilViewModel);
    }

    // GET: Perfil/Create
    [Route("novo-perfil")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult Create()
    {
      return View();
    }

    // POST: Perfil/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("novo-perfil")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult Create(PerfilViewModel perfilViewModel)
    {
      if (!ModelState.IsValid) return View(perfilViewModel);

      _perfilAppService.Register(perfilViewModel);

      return View(perfilViewModel);
    }

    // GET: Perfil/Edit/5
    [Route("editar-perfil/{id:guid}")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult Edit(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var perfilViewModel = _perfilAppService.GetPerfilById(id.Value);

      if (perfilViewModel == null)
      {
        return NotFound();
      }

      return View(perfilViewModel);
    }

    // POST: Perfil/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("editar-perfil/{id:guid}")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult Edit(PerfilViewModel perfilViewModel)
    {
      if (!ModelState.IsValid) return View(perfilViewModel);

      _perfilAppService.Update(perfilViewModel);

      // validar se a operacao ocorreu com sucesso

      return View(perfilViewModel);
    }

    // GET: Perfil/Delete/5
    [Route("excluir-perfil/{id:guid}")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var perfilViewModel = _perfilAppService.GetPerfilById(id.Value);

      if (perfilViewModel == null)
      {
        return NotFound();
      }

      return View(perfilViewModel);
    }

    // POST: Perfil/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Route("excluir-perfil/{id:guid}")]
    [Authorize(Policy = "PodeGravar")]
    public IActionResult DeleteConfirmed(Guid id)
    {
      _perfilAppService.Remove(id);

      //return RedirectToAction("Index");
      return RedirectToAction(nameof(Index));
    }
  }
}

Proj4Me.Web/Controllers/ProjetoAreaServicoController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proj4Me.Application.Interfaces;
using Proj4Me.Application.ViewModels;
using Proj4Me.Domain.Core.Notification;
using Proj4Me.Domain.Interfaces;

namespace Proj4Me.Web.Controllers
{
  //[Route("")]
  public class ProjetoAreaServicoController : BaseController
  {
    private readonly IProjetoAreaServicoAppService _projetoAreaServicoAppService;
    private readonly IColaboradorAppService _colaboradorAppService;
    private readonly IPerfilAppService _perfilAppService;

    public ProjetoAreaServicoController(IProjetoAreaServicoAppService projetoAreaServicoAppService, 
                                        IColaboradorAppService colaboradorAppService, 
                                        IPerfilAppService perfilAppService,
                                        IDomainNotificationHandler<DomainNotification> notifications,
                                        IUser user) : base(notifications, user)
    {
      _projetoAreaServicoAppService = projetoAreaServicoAppService;
      _colaboradorAppService = colaboradorAppService;
      _perfilAppService = perfilAppService;
    }

    // GET: ProjetoAreaServicoViewModels
    //[Route("")]
    [Route("listar-projetos")]
    public IActionResult Index()
    {
      RelatorioProjetosViewModel relatorio = new RelatorioProjetosViewModel();
      relatorio.ListaProjetos = new List<ProjetoAreaServicoViewModel>();

      var _listaProjetos = _projetoAreaServicoAppService.GetAll();

      foreach (var item in _listaProjetos)
      {
        relatorio.ListaProjetos.Add(new ProjetoAreaServicoViewModel
        {
          Id = item.Id,
          ColaboradorId = item.ColaboradorId,
          Descricao = item.Descricao,
          Nome = item.Nome,
          PerfilId = item.PerfilId,
          Colaborador = item.Colaborador,
          Perfil = item.Perfil
        });
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      // ViewData["ColaboradorId"].Add(0, "todos", "id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      return View(relatorio);
    }
    public ActionResult Filter(RelatorioProjetosViewModel model)
    {
      if (ModelState["PerfilId"].RawValue.Equals("Todos"))
        ModelState.Remove("PerfilId");
      if (ModelState["ColaboradorId"].RawValue.Equals("Todos"))
        ModelState.Remove("ColaboradorId");
      if (model.DataInicio > model.DataFim)
        ModelState.AddModelError("DataInicio", "A data inicial deve ser menor do que a data final");

      RelatorioProjetosViewModel relatorio = new RelatorioProjetosViewModel();
      relatorio.ListaProjetos = new List<ProjetoAreaServicoViewModel>();

      var _listaProjetos = _projetoAreaServicoAppService.GetAll();

      foreach (var item in _listaProjetos)
      {
        relatorio.ListaProjetos.Add(new ProjetoAreaServicoViewModel
        {
          Id = item.Id,
          ColaboradorId = item.ColaboradorId,
          Descricao = item.Descricao,
          Nome = item.Nome,
          PerfilId = item.PerfilId,
          Colaborador = item.Colaborador,
          Perfil = item.Perfil
        });
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      return View("Index", relatorio);
    }

    // GET: ProjetoAreaServicoViewModels/Details/5
    [Route("dados-do-projeto/{id:guid}")]
    public IActionResult Details(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoById(id.Value);
      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Create
    [Route("novo-projeto")]
    public IActionResult Create()
    {
      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      var testee = _perfilAppService.GetAll();
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");


      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("novo-projeto")]
    public IActionResult Create(ProjetoAreaServicoViewModel projetoAreaServicoViewModel)
    {
      if (!ModelState.IsValid) return View(projetoAreaServicoViewModel);

      _projetoAreaServicoAppService.Register(projetoAreaServicoViewModel);



      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Edit/5
    [Route("editar-projeto/{id:guid}")]
    public IActionResult Edit(Guid id)
    {
      if (id == null)
      {
        return NotFound();
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      var teste = _projetoAreaServicoAppService.GetProjetoColaboradorPerfil(id);
      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoColaboradorPerfil(id);

      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("editar-projeto/{id:guid}")]
    public IActionResult Edit(ProjetoAreaServicoViewModel projetoAreaServicoViewModel)
    {
      if (!ModelState.IsValid) return View(projetoAreaServicoViewModel);

      _projetoAreaServicoAppService.Update(projetoAreaServicoViewModel);

      // validar se a operacao ocorreu com sucesso

      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Delete/5
    [Route("excluir-projeto/{id:guid}")]
    public IActionResult Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoById(id.Value);

      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    // POST: ProjetoAreaServicoViewModels/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Route("excluir-projeto/{id:guid}")]
    public IActionResult DeleteConfirmed(Guid id)
    {
      _projetoAreaServicoAppService.Remove(id);

      //return RedirectToAction("Index");
      return RedirectToAction(nameof(Index));
    }
  }
}

Proj4Me.Web/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Acesso Negado!";
}

<header>
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-danger">Você não tem permissão para fazer esta ação!</p>
</header>

Proj4Me.Web/Views/Shared/_Layout.cshtml
@using Proj4Me.Domain.Interfaces
@inject IUser user

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proj4Me</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proj4Me</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (user.IsAuthenticated())
                {
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProjetoAreaServico" asp-action="Index">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colaborador" asp-action="Index">Colaboradores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Perfil" asp-action="Index">Perfis</a>
                        </li>
                    </ul>
                </div>
                }
                <div class="navbar-collapse collapse">
           @*         <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Eventos" asp-action="Index">Próximos Eventos</a></li>
                        @{
                            if (user.IsAuthenticated())
                            {
                                <li><a asp-area="" asp-controller="Eventos" asp-action="MeusEventos">Meus Eventos</a></li>
                            }
                        }
                    </ul>*@
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Proj4Me.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>