Proj4Me.Web/Controllers/ProjetoAreaServicoController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proj4Me.Application.Interfaces;
using Proj4Me.Application.ViewModels;
using Proj4Me.Domain.Core.Notification;
using Proj4Me.Domain.Interfaces;

namespace Proj4Me.Web.Controllers
{
  //[Route("")]
  public class ProjetoAreaServicoController : BaseController
  {
    private readonly IProjetoAreaServicoAppService _projetoAreaServicoAppService;
    private readonly IColaboradorAppService _colaboradorAppService;
    private readonly IPerfilAppService _perfilAppService;

    public ProjetoAreaServicoController(IProjetoAreaServicoAppService projetoAreaServicoAppService, 
                                        IColaboradorAppService colaboradorAppService, 
                                        IPerfilAppService perfilAppService,
                                        IDomainNotificationHandler<DomainNotification> notifications,
                                        IUser user) : base(notifications, user)
    {
      _projetoAreaServicoAppService = projetoAreaServicoAppService;
      _colaboradorAppService = colaboradorAppService;
      _perfilAppService = perfilAppService;
    }

    // GET: ProjetoAreaServicoViewModels
    //[Route("")]
    [Route("listar-projetos")]
    public IActionResult Index()
    {
      RelatorioProjetosViewModel relatorio = new RelatorioProjetosViewModel();
      relatorio.ListaProjetos = new List<ProjetoAreaServicoViewModel>();

      var _listaProjetos = _projetoAreaServicoAppService.GetAll();

      foreach (var item in _listaProjetos)
      {
        relatorio.ListaProjetos.Add(new ProjetoAreaServicoViewModel
        {
          Id = item.Id,
          ColaboradorId = item.ColaboradorId,
          Descricao = item.Descricao,
          Nome = item.Nome,
          PerfilId = item.PerfilId,
          Colaborador = item.Colaborador,
          Perfil = item.Perfil
        });
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      // ViewData["ColaboradorId"].Add(0, "todos", "id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      return View(relatorio);
    }
    public ActionResult Filter(RelatorioProjetosViewModel model)
    {
      if (ModelState["PerfilId"].RawValue.Equals("Todos"))
        ModelState.Remove("PerfilId");
      if (ModelState["ColaboradorId"].RawValue.Equals("Todos"))
        ModelState.Remove("ColaboradorId");
      if (model.DataInicio > model.DataFim)
        ModelState.AddModelError("DataInicio", "A data inicial deve ser menor do que a data final");

      RelatorioProjetosViewModel relatorio = new RelatorioProjetosViewModel();
      relatorio.ListaProjetos = new List<ProjetoAreaServicoViewModel>();

      var _listaProjetos = _projetoAreaServicoAppService.GetAll();

      foreach (var item in _listaProjetos)
      {
        relatorio.ListaProjetos.Add(new ProjetoAreaServicoViewModel
        {
          Id = item.Id,
          ColaboradorId = item.ColaboradorId,
          Descricao = item.Descricao,
          Nome = item.Nome,
          PerfilId = item.PerfilId,
          Colaborador = item.Colaborador,
          Perfil = item.Perfil
        });
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      return View("Index", relatorio);
    }

    // GET: ProjetoAreaServicoViewModels/Details/5
    [Route("dados-do-projeto/{id:guid}")]
    public IActionResult Details(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoById(id.Value);
      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Create
    [Route("novo-projeto")]
    public IActionResult Create()
    {
      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      var testee = _perfilAppService.GetAll();
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");


      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("novo-projeto")]
    public IActionResult Create(ProjetoAreaServicoViewModel projetoAreaServicoViewModel)
    {
      if (!ModelState.IsValid) return View(projetoAreaServicoViewModel);

      _projetoAreaServicoAppService.Register(projetoAreaServicoViewModel);



      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Edit/5
    [Route("editar-projeto/{id:guid}")]
    public IActionResult Edit(Guid id)
    {
      if (id == null)
      {
        return NotFound();
      }

      ViewData["ColaboradorId"] = new SelectList(_colaboradorAppService.GetAll(), "Id", "Nome");
      ViewData["PerfilId"] = new SelectList(_perfilAppService.GetAll(), "Id", "Nome");

      var teste = _projetoAreaServicoAppService.GetProjetoColaboradorPerfil(id);
      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoColaboradorPerfil(id);

      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [Route("editar-projeto/{id:guid}")]
    public IActionResult Edit(ProjetoAreaServicoViewModel projetoAreaServicoViewModel)
    {
      if (!ModelState.IsValid) return View(projetoAreaServicoViewModel);

      _projetoAreaServicoAppService.Update(projetoAreaServicoViewModel);

      // validar se a operacao ocorreu com sucesso

      return View(projetoAreaServicoViewModel);
    }

    // GET: ProjetoAreaServicoViewModels/Delete/5
    [Route("excluir-projeto/{id:guid}")]
    public IActionResult Delete(Guid? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var projetoAreaServicoViewModel = _projetoAreaServicoAppService.GetProjetoById(id.Value);

      if (projetoAreaServicoViewModel == null)
      {
        return NotFound();
      }

      return View(projetoAreaServicoViewModel);
    }

    // POST: ProjetoAreaServicoViewModels/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Route("excluir-projeto/{id:guid}")]
    public IActionResult DeleteConfirmed(Guid id)
    {
      _projetoAreaServicoAppService.Remove(id);

      //return RedirectToAction("Index");
      return RedirectToAction(nameof(Index));
    }
  }
}

Proj4Me.Web/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Proj4Me.Domain.Core.Notification;
using System.Threading.Tasks;

namespace Proj4Me.Web.ViewComponents
{
  public class SummaryViewComponent : ViewComponent
  {
    private readonly IDomainNotificationHandler<DomainNotification> _notifications;

    public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications)
    {
      _notifications = notifications;
    }

    /// <summary>
    /// Todo componente precisa ter um metodo que seja async que retorna um IViewComponentResult
    /// </summary>
    /// <returns></returns>
    public async Task<IViewComponentResult> InvokeAsync()
    {
      //TASK.FROMRESULT = invoca métodos não assincronos para assincrono
      var notificacoes = await Task.FromResult(_notifications.GetNotifications());// pega as notificações 
      notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));// para cada notificacao é colocado dentro do modelstate

      return View();
    }
  }
}

Proj4Me.Web/Views/ProjetoAreaServico/Create.cshtml
@model Proj4Me.Application.ViewModels.ProjetoAreaServicoViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProjetoAreaServicoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <hr />
            @*   chamando o viewcomponent*@
            <vc:summary />

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            @*            <div class="form-group">
                <label asp-for="ColaboradorId" class="control-label"></label>
                <input asp-for="ColaboradorId" class="form-control" />
                <span asp-validation-for="ColaboradorId" class="text-danger"></span>
                </div>*@
            <div>
                <div class="form-group">
                    <select asp-for="ColaboradorId" asp-items="ViewBag.ColaboradorId" size="1" class="form-control"></select>
                    <span asp-validation-for="Colaborador.Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <select asp-for="PerfilId" asp-items="ViewBag.PerfilId" size="1" class="form-control"></select>
                <span asp-validation-for="Perfil.Nome" class="text-danger"></span>
                <span asp-validation-for="PerfilId" class="text-danger"></span>
            </div>
            @*    <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class ="form-control" asp-items="ViewBag.ClienteId"></select>
                </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
    ValidacoesEvento();
    </script>

    <script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
    toastr["success"]("are you the six fingered man?");
    </script>
}

Proj4Me.Web/Views/ProjetoAreaServico/Delete.cshtml
@model Proj4Me.Application.ViewModels.ProjetoAreaServicoViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjetoAreaServicoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Perfil)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Perfil.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Colaborador)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Colaborador.Nome)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Proj4Me.Web/Views/ProjetoAreaServico/Details.cshtml
@model Proj4Me.Application.ViewModels.ProjetoAreaServicoViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProjetoAreaServicoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Perfil)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Perfil.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Colaborador)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Colaborador.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Proj4Me.Web/Views/ProjetoAreaServico/Edit.cshtml
@model Proj4Me.Application.ViewModels.ProjetoAreaServicoViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProjetoAreaServicoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div>
                <div class="form-group">
                    <select asp-for="ColaboradorId" asp-items="ViewBag.ColaboradorId" size="1" class="form-control"></select>
                    <span asp-validation-for="Colaborador.Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <select asp-for="PerfilId" asp-items="ViewBag.PerfilId" size="1" class="form-control"></select>
                <span asp-validation-for="Perfil.Nome" class="text-danger"></span>
                <span asp-validation-for="PerfilId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Proj4Me.Web/Views/ProjetoAreaServico/Index.cshtml
@*@model IEnumerable<Proj4Me.Application.ViewModels.ProjetoAreaServicoViewModel>*@
@model Proj4Me.Application.ViewModels.RelatorioProjetosViewModel
@{
    ViewData["Title"] = "Index";
}



<h1>Index</h1>

<div class="row">
    <div class="col-md-12">
        <div class="pull-left">
            <a asp-action="Create">
                <span title="Novo Evento" class="glyphicon glyphicon-plus-sign"></span>
            </a>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Filter">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <hr />
            @*   chamando o viewcomponent*@
            <vc:summary />
            <div class="row">
                <div class="form-group" padding-right="25px">
                    <label asp-for="DataInicio" class="control-label"></label>
                    <input asp-for="DataInicio" class="form-control datepicker" type="Date" data-val="true" />
                    @*@Html.Partial("_Categoria")*@
                    <span asp-validation-for="DataInicio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="DataFim" class="control-label"></label>
                    <input asp-for="DataFim" class="form-control datepicker" type="Date" data-val="true" />
                    <span asp-validation-for="DataFim" class="text-danger"></span>
                </div>
                <div>
                    <label class="control-label">Colaborador</label>
                    <div class="inline-block">
                        <select asp-for="ColaboradorId" asp-items="ViewBag.ColaboradorId" size="1" class="form-control">
                            <option>Todos</option>
                        </select>

                    </div>
                </div>
                <div class="inline-block">
                    <label class="control-label">Perfil</label>
                    <select asp-for="PerfilId" asp-items="ViewBag.PerfilId" size="1" class="form-control">
                        <option>Todos</option>
                    </select>
                    <span asp-validation-for="NomePerfil" class="text-danger"></span>

                </div>
                @*    <div class="form-group">
                        <label asp-for="ClienteId" class="control-label"></label>
                        <select asp-for="ClienteId" class ="form-control" asp-items="ViewBag.ClienteId"></select>
                    </div> *@
                <div class="inline-block">
                    <div class="form-group">
                        <input type="submit" value="Filtrar" class="btn btn-primary" />
                    </div>
                    <div></div>
                </div>
        </form>
    </div>
    <br />


</div>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.NomeProjeto)*@
                Nome Projeto
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ListaProjetos. Descricao)*@
                Descrição
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Perfil)*@
                Perfil
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Colaborador)*@
                Colaborador
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ListaProjetos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Perfil.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Colaborador.Nome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id"> Detalhe</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



    <script>
        ValidacoesEvento();
    </script>


}